### ISSUE TITLE
Import A pipeline from B pipeline ?

### ISSUE THREAD

**Issue by eromoe** [ploomber/ploomber#1084]
Hi, I have a common steps in several pipeline.  

For example: 

A pipeline
```
tasks:
  - source: tasks.raw.get
    product: products/data_{{basefreq}}/kline.pkl
    params:
      basefreq: '{{basefreq}}'

  - source: scripts/pp_features.py
    product: 
      nb: products/pp_features.ipynb
      data: products/data_{{basefreq}}/pp_features.pkl

  - source: scripts/pp_labeling.py
    params:
      freq: 'minutes'
    product: 
      nb: products/pp_labeling.ipynb
      data: products/data_{{basefreq}}/pp_labeling.pkl

  - source: scripts/pp_xy.py
    product:
      nb: products/pp_xy.ipynb
      X: products/data_{{basefreq}}/X.pkl
      y: products/data_{{basefreq}}/y.pkl
```

B pipeline
```
- import A
  - source: scripts/pp_train.py
    product:
      nb: products/pp_train.ipynb
      model: products/model_{{basefreq}}/pp_train_{{train_start_date}}~~{{train_end_date}}.pkl
    params:
      auto_model_path: '{{auto_model_path}}'
      train_start_date: '{{train_start_date}}'
      train_end_date: '{{train_end_date}}'
      test_start_date: '{{test_start_date}}'
      test_end_date: '{{test_end_date}}'

  - source: scripts/pp_predict_raw.py
    product:
      nb: products/pp_predict_raw.ipynb
      pred: products/model_{{basefreq}}/pred/train_{{train_start_date}}~~{{train_end_date}}_test_{{test_start_date}}~~{{test_end_date}}.pkl
      stats: products/model_{{basefreq}}/stats/train_{{train_start_date}}~~{{train_end_date}}_test_{{test_start_date}}~~{{test_end_date}}.pkl
    params:
      train_start_date: '{{train_start_date}}'
      train_end_date: '{{train_end_date}}'
      test_start_date: '{{test_start_date}}'
      test_end_date: '{{test_end_date}}'
```

There is also a C pipeline : 
```
- import A
  - source: scripts/other_research_on_same_data.ipynb
```

----

Because B and C share same data, this feature is very useful.
