### ISSUE TITLE
Pipelines with python path and scripts

### ISSUE THREAD

**Issue by OscarIntellico** [ploomber/ploomber#1172]
# Pipelines with Python Path and Scripts

Hi Team,

I have created a pipeline with two tasks:

1. **Download a file from a remote location**:
   - This task is very routine, so I wrote a reusable function to handle it.

2. **Analyze the downloaded data**:
   - This task is highly customized and handled via a standalone script.

Here’s the pipeline definition:

```yaml
meta:
  extract_upstream: false

tasks:
  - source: commons.download.download_file
    name: download
    product: file.csv

  - source: ../scripts/analysis/analyze_file.py
    name: analyze_file
    product:
      nb: ../products/analysis/analyze_file.ipynb
```

## Project Structure
Our team follows a specific folder structure for development. The `commons/` folder contains shared source code, while the `project/` folder is used for managing the Ploomber project. The structure is as follows:

```
root/
├── commons/
│   └── download.py
├── project/
│   ├── pipelines/
│   │   └── pipeline.yaml
│   ├── scripts/
│   │   └── analysis/
│   │       └── analyze_file.py
│   └── products/
```

## Issue
When running `ploomber scaffold -e project/pipelines/pipeline.yaml`, I encounter a module error because the `commons` folder is not found. However, other commands like `nb`, `sync`, and `build` work without issues.

The issue arises whenever the `pipeline.yaml` file is placed inside a subfolder (e.g., `project/pipelines/`). If the `pipeline.yaml` file is located at the root level, everything works as expected.

### Steps Taken to Resolve
I attempted to use the lazy_load function inside an interactive python environment (it was suggested by the documentation), but this did not resolve the issue.

### Request
I’d appreciate guidance on the following:
- Best practices for organizing pipelines when working with shared code in a different folder.
- Suggestions to address the module path issue when the `pipeline.yaml` file is not at the root level.

### Workaround
I wrote  a bash script that scaffolds for me the python tasks, but now i need to give to all of my teamates this script.

Thank you for your help!
