### ISSUE TITLE
TestSpec

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#180]
Support integration testing (via the `on_finish`) hook using specs:

Proposed API:

```yaml
tasks:
  - source: some_script.sql # or .py
    on_finish:
      no_nulls_in_columns: [a, b, c]
      distinct_values_in_columns: [b, c]
```

This should be implemented in a TestSpec class (similar to DAGSpec).

Could also be useful in the PythonAPI for on_finish hooks, since they provide more flexibility, they should integrate with data_frame_validator, and a (not implemented yet) equivalent for sql
