### ISSUE TITLE
How to download a file from a URL in a function?

### ISSUE THREAD

**Issue by rdmolony** [ploomber/ploomber#308]
I'd like to call a download function from within `pipeline.yaml` and pass it a URL in order to split out any file downloading from any cleaning roughwork `py` notebooks with something like:

Run `ploomber build` on:
- `pipeline.yaml`: 
  ```yaml
  tasks:
    - source: download.download_file_from_url
      name: Download sample1.csv
      upstream:
        url: "https://filesamples.com/samples/document/csv/sample1.csv"
      product:
        data: output/sample1.csv
  ```
- `download.py`: 
  ```python
  from urllib.request import urlretrieve
  
  def download_file_from_url(product, upstream):
      urlretrieve(url=upstream["url"], filename=product["data"])
    ```

which produced
```python-traceback
ValueError: Error validating task "{'source': 'download.download_file_from_url', 'name': 'Download sample1.csv', 'upstream': {'url': 'https://filesamples.com/samples/document/csv/sample1.csv'}, 'product': {'data': 'output/sample1.csv'}}", if meta.extract_upstream is set to True, tasks should not have an "upstream" key
```
>  I didn't expect this to work as from the docs it seems that upstream is predominantly filepath-related!

---

I tried closing the URL within the download function to avoid the `upstream` parameter with files:
- `pipeline.yaml`: 
  ```yaml
  tasks:
    - source: download.download_file_from_url
      name: Download sample1.csv
      product:
        data: output/sample1.csv
    ```
- `download.py`: 
  ```python
  from urllib.request import urlretrieve
  
  def download_file_from_url(product, url):
      url = "https://filesamples.com/samples/document/csv/sample1.csv"
      urlretrieve(url=url, filename=product["data"])
    ```
which produced:
```python-traceback
Could not get "download_file_from_url" from module "download" (loaded from: C:\Users\Rowan\code-wd\geodata-notebooks\download.py), make sure it is a valid callable defined in such module. You can also set the task class using the "class" key
```

---

Is this possible or recommended to do this with `ploomber`?  I really like the idea of using `ploomber` as the pipework for reproducing roughwork notebook scripts with one script per dataset wrangling - if I can I want to avoid hardcoding download URLs into these notebooks!

---
Note:
- Ploomber: v0.11.1 installed from `conda-forge`
- Files:
  ```powershell
  C:.
  │   download.py
  │   pipeline.yaml
  ```

**Comment by edublancas** [comment]
Hi,

`upstream` is meant to be used to refer to other tasks by name and set execution dependencies. e.g., given two tasks:

```
A -> B
```

We say A is upstream of B. So anything that is in `upstream` must be a task name. Usually, users don't set this option in `pipeline.yaml` because it is extracted from the source code itself. e.g., in a notebook/script:

```python
# B.py
upstream = ['A']
```

Or if using a function:

```python
def my_task(product, upstream):
    # ploomber parses this reference to A
    df = pd.read_csv(upstream['A'])
```


What you want to use is the `params` key:

```yaml
tasks:
  - source: download.download_file_from_url
    params:
      url: "https://filesamples.com/samples/document/csv/sample1.csv"
    product:
      data: output/sample1.csv
```

Then add a `url` param to your function:

```python
def my_task(product, url):
    # do things with URL
```

Let me know if that works for you!
