### ISSUE TITLE
Tracking changes in external files

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#310]
Incremental builds allow users to quickly iterate since Ploomber takes care of only executing tasks whose source code or parameters have changed since the last run. However, if the source code is loading external files, changes to them are not detected:

```python
from pathlib import Path

def my_task(product, upstream):
    # changes to some/path.json are not detected!
    content = Path('some/path.json').read_text()
    # do stuff
    # ...
    Path(product).write_text(output)
```

We're looking for a way to enhance this functionality in the simplest possible way for the user. The cleanest approach we've found so far is to embed this logic in `tasks[*].params`:

```yaml
# pipeline.yaml
tasks:
    - source: my_module.my_task
      product: output.txt
      params:
        json_file: some/path.json
```

Then our code would look like this:

```python
def my_task(product, upstream, json_file):
    content = Path(json_file).read_text()
    # do stuff
    # ...
    Path(product).write_text(output)
```

The main benefit is that this is task-agnostic: it works the same whether it's a function, script, or notebook.

However, for a given task, not all parameters are paths to files. Users may not want to trigger task execution on changes to all external files, so they need a way to distinguish between params and files that trigger task execution.

## Option 1: Naming convention

One way to achieve this without any API changes is to have a naming convention. Say, add a suffix (e.g., `resource` to tell Ploomber also to track files content):

```yaml
# pipeline.yaml
tasks:
    - source: my_module.my_task
      product: output.txt
      params:
        # track contents of this file
        json_file: some/path-resource.json
        # do not track this
        json_file_another: another/path.json
```

## Option 2: Special type of parameters

Alternatively, we may define a special type of param:

```yaml
# pipeline.yaml
tasks:
    - source: my_module.my_task
      product: output.txt
      params:
        # track contents of this file
        json_file:
            # special type of parameter defined by the resource key
            resource: some/path.json
        # do not track this
        json_file_another: another/path.json
```

## Important considerations

1. File size: To keep the metadata file size small, we should only save the file hash, not its contents

**Comment by filipj8** [comment]
@edublancas This looks great! I prefer Option 2, as the end user is explicitly stating that they want that file tracked by ploomber. With Option 2 there's less chance of accidental tracking and more flexibility with file names. 

How would the resource file in Option 2 be referenced in the tasks? `json_file['resource']`? Would the special `resource` parameter behavior only be triggered in the 2nd level of params? 

Building off of Option 2, another option that might work well is to have a special suffix that the user can add to params to indicate they should be tracked as resources (e.g. `json_file__resource: some/path.json`).

**Comment by edublancas** [comment]
I like the suggestion of using a suffix in the param name rather than the filename:

```yaml
# pipeline.yaml
tasks:
    - source: my_module.my_task
      product: output.txt
      params:
        # track contents of this file
        json_file__resource: some/path.json
        # do not track this
        json_file_another: another/path.json

```

Inside the task:

```python
from pathlib import Path

def my_task(product, upstream, json_file__resource):
    content = Path(json_file__resource).read_text()
    # do stuff
    # ...
    Path(product).write_text(output)
```

Or if it's a notebook/script the injected cell would be like this:

```python
# injected cell
json_file__resource = 'some/path.json'
```

What do you think?

I'm guessing you're suggesting a double underscore to prevent tracking files by accident?

**Comment by filipj8** [comment]
Yup this looks great! The double underscore would be helpful for preventing accidental tracking, as well as make it a little more obvious that it's a special suffix that has specific meaning to ploomber.

**Comment by fferegrino** [comment]
imo, the double underscore starts to veer into the territory of configuration, at that point I'd prefer to have a explicit `track` parameter: 
```yaml
tasks:
    - source: my_module.my_task
       product: output.txt
       track:
           - some/path-resource.json
           - some_code.py
```

I also had this issue, at the moment it feels like you must put all your task's code within the same file if you want your changes to be executed the next time you build the pipeline, this is infeasible if the code is already modularised/split in functions.

**Comment by edublancas** [comment]
One issue with adding a new section to the YAML spec is that it may be confusing for users because both values in `track` and `params` will end up in the same place (i.e., function arguments or injected cell in a notebook/script).

@fferegrino your second point is really important, and that's something it's been on the to-do list for a while. Detecting changes on imported modules is technically feasible but it isn't a trivial feature, it involves some heavy static analysis.

Example:

```python
# ploomber won't detect changes to my_function!
from my_module import my_function

def my_task(product):
    result = my_function()
```

The most elegant solution is to run static analysis on the code, find all imports, retrieve their source location and track the contents of those files. However, that has to be a recursive process since `my_function` may also import other files we want to track.

As a temporary fix, people can use the feature under discussion:

```yaml
# pipeline.yaml
tasks:
    - source: my_module.my_task
      product: output.txt
      params:
        # track contents of this file
        python__resource: my_module/my_function.py
```

But long-term, this isn't what we want.

**Comment by edublancas** [comment]
If you're interested in the detecting changes on imported modules issue, check out #111

**Comment by edublancas** [comment]
While working on the implementation, I thought of an alternative: having a sub-section under params.

```yaml
# pipeline.yaml
tasks:
    - source: my_module.my_task
      product: output.txt
      params:
        # track everything here....
        resources:
          json_file: some/path.json
        # regular, untracked params...
        another_param: 1
```

```python
from pathlib import Path

def my_task(product, upstream, resources):
    content = Path(resources['json_file']).read_text()
    # do stuff
    # ...
    Path(product).write_text(output)
```

What do you think? @filipj8   @fferegrino
