### ISSUE TITLE
Simplify API for tasks with multiple products

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#316]
# Summary

* `@serializer` takes care of calling the function once for every product (even if task generates multiple products).
* `@unserializer` is similar to `@serializer`
* `@serializer` and `@unserializer` take an argument to choose what function to use depending on the extension
* Provide default implementations for common formats (csv, parquet, txt)
* Provide a generic implementation (pickle, joblib)

# API

## Generic implementation

Easiest solution to get started:

```yaml
# all products (generated by function tasks) are pickled
serializer: ploomber.serializer_pickle
unserializer: ploomber.unserializer_pickle

tasks:
    # one_product is a function
    - source: tasks.one_product
      product: one_product.pickle
```

## Creating (un)serializer functions

If a user wants to customize serialization functions:

```python
from ploomber import serializer, to_csv, write_text

# ploomber provides some defaults (csv, txt), but users can supply their own
@serializer({'csv': to_csv, 'txt': write_text})
def my_serializer(obj, product):
    # runs if none of the dispatchers match
    raise TypeError('Unsupported product')
```

Or, you can use the `fallback` argument to use `pickle` to every product
that does not have a registered serializer:

```python
@serializer({'csv': to_csv, 'txt': write_text}, fallback=True)
def my_serializer(obj, product):
    pass
```

`fallback` can take other values: `'joblib'`, and `'cloudpickle'` to use
alternative serializers.

Unserializers have the same API:

```python
@unserializer({'csv': read_csv, 'txt': read_text})
def my_unserializer(product):
    # provide a default implementation
    pass
```

## Adding tasks

Say we have the following pipeline:

```yaml
tasks:
    - source: tasks.one_product
      product: one_product.pickle

    - source: tasks.one_product_dict
      product: one_product_dict.pickle

    - source: tasks.many_products
      product:
        one: one.pickle
        two: two.pickle
```

Simplest case, value returned is serialized:

```python
def one_product(upstream):
    # df stored to one_product.pickle
    return df
```

This applies for all types of objects:

```python
def one_product_dict(upstream):
    # dict stored to one_product_dict.pickle
    return dict(a=1, b=2)
```

However, if the task declaration in the `pipeline.yaml` has multiple products, it must return a dictionary with the same keys:

```python
def many_products(upstream):
    # df_one stored to one.pickle
    # df_two stored to two.pickle
    return dict(one=df_one, two=df_two)
```
