### ISSUE TITLE
"ploomber install" (with conda) fails on Windows

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#319]
A user reported on Slack that `ploomber install` fails with the error complaining that pip is not installed.

Copied from Slack:

> when ploomber scaffold is run, the following ploomber install successfully creates  fully pip-based conda env. However polluting conda env with pip is generally discouraged, so I tried ploomber scaffold --conda, which, after install, failed with  the error I reported earlier. The 3rd variant was the same conda scaffold but with changed environmnt.yml (pip: to conda:). That failed the same way after install. Now, when I created environments explicitly (conda env create -f=./environment.yml)  on variant 2 and 3, both successfully created their respective environments. Their content was: 2 -> a mixed env (92x pip + 11x conda packages); 3 -> fully conda-based.

**Comment by edublancas** [comment]
Update:

The problem happens because Ploomber cannot find the pip executable after creating the environment, this is surprising since the `environment.yml` contains `pip` as a dependency so please confirm the `environment.yml` contents are like this:


```yaml
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - conda:
    - pip
    - matplotlib
    - seaborn
    - pandas
    - scikit-learn
    - ploomber
```

Please run this in the Python console (prints conda's location):

```
python -c "import shutil; from pathlib import Path; print(Path(shutil.which('conda')).parents[1])"
```

Then go to the printed directory and let me know if:

1. There is a `Scripts` directory inside the printed directory
2. There is a `pip.exe` file inside `Scripts`
