### ISSUE TITLE
How to specify a task with no product?

### ISSUE THREAD

**Issue by rdmolony** [ploomber/ploomber#326]
I want to load my s3 credentials as environmental variables in a task that has no `product`

I can use `python-dotenv` to load environmental variables saved in a `.env` file

environmental_variables.py:
```python
from typing import Any

from dotenv import load_dotenv


def load_environmental_variables(product: Any):
    load_dotenv()
```

- Excluding `product` raises `KeyError`:

pipeline.yaml:

```yaml
tasks:
  - source: environmental_variables.load_environmental_variables
    name: load_environmental_variables
```
```python-traceback
KeyError: "Error validating TaskSpec({'source': 'environmental_variables.load_environmental_variables', 'name': 'load_environmental_variables', 'upstream': None}). Missing keys: {'product'}"
```

- Setting `product=None` raises `TypeError`

pipeline.yaml:

```yaml
tasks:
  - source: environmental_variables.load_environmental_variables
    name: load_environmental_variables
product: None
```
```python-traceback
TypeError: Error initializing File with argument None (expected str, bytes or os.PathLike object, not NoneType
```

Keywords: secrets, environmental variables, credentials

**Comment by rdmolony** [comment]
A bit of a hack but I can specify product="" and the pipeline runs fine

pipeline.yaml:

```yaml
tasks:
  - source: environmental_variables.load_environmental_variables
    name: load_environmental_variables
product: ""
```

**Comment by edublancas** [comment]
Tasks are required to generate outputs to enable the incremental builds feature, so if anything does not generate an output, it's best to do it in a different way. But this is great feedback, I'll modify the docs to make sure this distinction is clear!

There are a few options  here:

1. load your env variables before calling ploomber build

```sh
# command to load your env variables

# then call ploomber build
ploomber build
```

2. load environment variables at the beginning of each task that needs them

```python
from dotenv import load_dotenv

def some_task(product):
    load_dotenv()
    # do stuff with env variables
```

3. use an `on_render` hook

`on_render` allows you to execute arbitrary code before a task executes. Assuming `tasks.raw.get` is your first task, you could do something like this:

```yaml
tasks:
  - source: tasks.raw.get
    product: products/raw/get.csv
    # load env vars before executing the task!
    on_render: hooks.load_env_var

  - source: tasks.features.sepal
    product: products/features/sepal.csv

  - source: tasks.features.petal
    product: products/features/petal.csv

  - source: tasks.features.features
    product: products/features/features.csv

  - source: scripts/fit.py
    product:
      nb: products/report.html
      model: products/model.pickle
```

This is a task-level hook but since you're modifying `os.environ`, other tasks can see the change. There are also dag-level hooks that are more appropriate for this use case (e.g., your code for loading env vars executes before any task executes) but I haven't ported them to the YAML API yet.

**Note**

This is applicable only for function tasks, if you're using notebooks, then you have to go with option 2. Since Jupyter kernel processes are not child processes of ploomber's process, they won't see the changes to `os.environ`.

Hope that helps!

**Comment by rdmolony** [comment]
Fantastic, thanks a lot @edublancas, that's very clear!

**Comment by rdmolony** [comment]
I should add my preference here is `on_render`, gets in your way the least out of all three imo

**Comment by rdmolony** [comment]
A dag level hook would be useful for my `create_folder_structure` hook (ref ploomber/ploomber#327):

```python
from pathlib import Path

def create_folder_structure(dirname: str, product: Any) -> None:
    dirpath = Path(dirname)
    dirpath.mkdir(exist_ok=True)
    (dirpath / "external").mkdir(exist_ok=True)
    (dirpath / "processed").mkdir(exist_ok=True)
    (dirpath / "html").mkdir(exist_ok=True)
    (dirpath / "notebooks").mkdir(exist_ok=True)
```

**Comment by rdmolony** [comment]
I'll close this for now as the Q is answered

**Comment by rdmolony** [comment]
Or equivalently I could run:

hooks.py

```python
from pathlib import Path
from typing import Any

def create_folder_structure(product: Any) -> None:
    dirpath = Path("data")
    dirpath.mkdir(exist_ok=True)
    (dirpath / "external").mkdir(exist_ok=True)
    (dirpath / "processed").mkdir(exist_ok=True)
    (dirpath / "html").mkdir(exist_ok=True)
    (dirpath / "notebooks").mkdir(exist_ok=True)
```

pipeline.yaml:

```yaml
tasks:
  - source: hooks.create_folder_structure
    name: create_folder_structure
    product: "data/"
```
