### ISSUE TITLE
How to pass a list to a ploomber task?

### ISSUE THREAD

**Issue by rdmolony** [ploomber/ploomber#327]
I want to create a folder structure so my `gpd.GeoDataFrame.to_file` operations don't raise an error if the directory they are being saved to doesn't exist

folders.py
```python
from pathlib import Path
from typing import Any
from typing import List

def create_folder_structure(folders: List[str], upstream: Any, product: str) -> None:
    for folder in folders:
        folderpath = Path(folder)
        if not folderpath.exists():
            folderpath.mkdir()
```

pipeline.yaml:

```yaml
tasks:
  - source: folders.create_folder_structure
    name: create_folder_structure
    params: ["data", "data/external", "data/processed", "data/html", "data/notebooks"]
    product: ""
```

Calling this pipeline with `ploomber build` raises:
```python-traceback
TypeError: Error initializing PythonCallable from {'source': <function create_folder_structure at 0x000001B3D0E204C0>, 'name': 'create_folder_structure', 'params': ['data', 'data/external', 'data/processed', 'data/html', 'data/notebooks'], 'product': '', 'class': <class 'ploomber.tasks.tasks.PythonCallable'>}. Error: Params must be initialized with a mapping, got: ['data', 'data/external', 'data/processed', 'data/html', 'data/notebooks'] ('list')
```

---

It seems that currently the spec api only supports key value mappings, so perhaps this isn't implemented!
