### ISSUE TITLE
Add support for lists and wildcard in resources_

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#361]
Add list support for resources_:

```yaml
tasks:
    - source: scripts/my-script.py
      product: report.html
      params:
        resources_:
            files: [a.json, b.json]
```

(should track changes to a.json and b.json)

And support for glob-like expressions:

```yaml
tasks:
    - source: scripts/my-script.py
      product: report.html
      params:
        resources_:
            file: prefix-*.json
```

(should track all files that start with prefix-)

docs: https://ploomber.readthedocs.io/en/latest/api/spec.html?highlight=resources_#tasks-params-resources
