### ISSUE TITLE
env.yaml converts numeric-looking strings to float

### ISSUE THREAD

**Issue by reesehopkins** [ploomber/ploomber#433]
### env.yaml

```yaml
my_param: ['A','B','2E-03']
```
### pipeline.yaml
```yaml
tasks:
  - source: test_strings.py
    params:
        my_param: "{{my_param}}"
    product:
      nb: test_strings.ipynb
 ```

### test_strings.py

```python
# + tags=["parameters"]
upstream = None
product = None
my_param= None
# -

my_param
```

This will result in my_param as `['A','B',0.02]` instead of `['A','B','2E-02']`. Definitely an edge case - but using the `yaml` library will give the expected result.
