### ISSUE TITLE
Do not connect to client if tasks previously run

### ISSUE THREAD

**Issue by reesehopkins** [ploomber/ploomber#438]
For some of my projects, I need to connect to 3+ databases. When I run `ploomber build`, it connects to the client each time -- even if the task is not outdated. 

It would be nice if ploomber could recognize these tasks has already been run without invoking the client. This way I could continue to developing locally without internet connectivity (and save a few seconds each time I build because I don't need to connect to the clients).

**Comment by edublancas** [comment]
Interesting, can you provide some more details?

* which client you're using (I think it's DBClient, right?) for tasks
* which client you're using for products

Clients open connections lazily. for task clients, they only open a connection when they have to execute a query in the database, for product clients, they open a connection when checking task's status (outdated/up-to-date), so my guess is that the latter is connecting to the database

**Comment by reesehopkins** [comment]
Thanks for the details!! 

Yes, I think ploomber is connecting to my DBClient client to check a task's status. Unfortunately, I need several database clients as our data is scattered across various systems. If I am reading the docs correctly, it means I need to define the client for each task in my `pipeline.yml` file, right? Or can I configure multiple clients at the "top-level" of the `pipeline.yml` file (instead of inside each task).

Normally, it's not a big deal, but I work remotely and one database takes ~60 seconds to create a connection. 

Not sure if I have task or product clients. Here's a snippet of my `pipeline.yml`. It doesn't have a client section.

```yaml
tasks:    
  - source: 'query-a.sql'
    product: 'output-a.parquet'
    client: config.fast_database

  - source: 'query-b.sql'
    product: 'output-b.parquet'
    client: config.slow_database

```

**Comment by edublancas** [comment]
Yes, you can declare top-level clients. That should lower your connection time since ploomber will use the same connection for all tasks.

Looks like all your tasks are dumping data so the config would look like this:

```yaml
clients:
    SQLDump: db.slow_database

tasks:    
  - source: 'query-a.sql'
    product: 'output-a.parquet'
    # this overrides db.slow_database
    client: config.fast_database

  - source: 'query-b.sql'
    product: 'output-b.parquet'
    # no need to have a client here anymore
```

Let me know if this config helps you with connection time. Unfortunately, right now, there isn't a way to configure more than one top-level client. So you'd still need to declare your `config.fast_database` on each task. However, this is a great point and I think we should support this.

So as a quick measure, let me know if adding this top-level client helps, then we can work on a solution so you can configure more than one top-level client.

Thanks a lot for your feedback!
