### ISSUE TITLE
Add global option to set chunksize to null

### ISSUE THREAD

**Issue by reesehopkins** [ploomber/ploomber#439]
For some projects, I don't need to chunk my data. It'd be nice to have a global variable I could specify in the `pipeline.yaml` file to avoid setting chunksize to null for every SQL task in a pipeline.

If implemented, I don't know if should go in the `clients` or `meta` sections.

**Comment by edublancas** [comment]
Thanks for opening the issue!

Yes, I agree we could simplify this a bit. I'm wondering if we should make `chunksize: null` the default value. 

But regardless, I'm thinking we could have a section to declare default values to avoid repetition, something like:

```yaml
constructor_defaults:
    SQLDump:
        chunksize: null

tasks:
   # all SQLDump tasks use chunksize: null
```

What do you think?
