### ISSUE TITLE
Changing chunksize does not trigger rebuild

### ISSUE THREAD

**Issue by reesehopkins** [ploomber/ploomber#440]
### pipeline.yaml
```yml
tasks:
    - source: query.sql
      product: data.parquet
```

### query.sql

```sql
select * from table 
```

When adding `chunksize: null` in the `pipeline.yaml`, the task is not rerun when calling `ploomber build`

**Comment by edublancas** [comment]
Hi,

thanks for reporting this. to know what tasks to run or skip, ploomber stores a metadata file with source code and task params (the `params` key in a task's spec in `pipeline.yaml`):

```yaml
tasks:
    - source: query.sql
      product: data.parquet
      params:
         a_param: value
```

However, any other values (such as `chunksize`) are not saved. I'll add this to the backlog.

In case anyone is interested in fixing this, here's the line where we update a task's metadata:

https://github.com/ploomber/ploomber/blob/ecc5d0346db3b415c3845025aafcf2c8aff08e90/src/ploomber/tasks/abc.py#L355

This is the method that needs updating:

https://github.com/ploomber/ploomber/blob/ecc5d0346db3b415c3845025aafcf2c8aff08e90/src/ploomber/products/metadata.py#L230

A few ideas on the implementation:

Add a method to the Task abstract class that collects all constructor params (except params) so we can store them in the metadata, ignoring the ones that cannot be serialized

https://github.com/ploomber/ploomber/blob/master/src/ploomber/tasks/abc.py
