### ISSUE TITLE
Scaffold support for R files

### ISSUE THREAD

**Issue by jaesmin** [ploomber/ploomber#476]
Hello! 
Running `ploomber scaffold` with a pipeline.yaml containing .R or .Rmd files returns this error, "This command does not support adding tasks with extension ".R", valid ones are .py and .sql." 

Is `scaffold` able to create a pipeline with R files?

Thank you,
Jae

**Comment by edublancas** [comment]
Hi @jaesmin!

Unfortunately, `ploomber scaffold` does not work with `.R/.Rmd` files yet,  but thanks for reporting this, we'll add it to the roadmap for the next release 😊

In the meantime, you can use our R example to get started quickly: https://github.com/ploomber/projects/tree/master/templates/spec-api-r

If you have ploomber installed, you can get the example executing:

```sh
ploomber examples -n templates/spec-api-r -o r-example
```

Then move to the `r-example`  folder and execute:

```sh
ploomber build
```

Note that for R to work with Ploomber, you need to install and configure `IRKernel`, check out the instructions here: https://docs.ploomber.io/en/latest/user-guide/r-support.html#configuring-r-environment

Let me know if you're able to run the R example, if you have further questions, you can join our Slack community: https://ploomber.io/community

Thanks for your feedback!

**Comment by edublancas** [comment]
Hi, this has been fixed in Ploomber 0.14.5

Quick example:

```sh
# upgrade
pip install ploomber --upgrade

# get example
ploomber examples -n templates/spec-api-r -o example

# move to folder
cd example
```

Edit `pipeline.yaml` (e.g., here I add a new task at the end):

```yaml
tasks:
  # use plain R scripts
  - source: raw.R
    product:
      # this is the executed version of your script
      # you can review tables and charts here
      nb: output/raw.html
      data: output/raw.csv

  - source: clean.R
    product:
      nb: output/clean.html
      data: output/clean.csv

  # R markdown files also supported
  - source: plot.Rmd
    product: output/plot.html

  # my new task
  - source: new-task.Rmd
    product: output/new-task.html
```

Then:

```sh
# add new task
ploomber scaffold

# build pipeline
ploomber build
```

If you're using RStudio, you can run the following to inject input paths on each file:

```sh
# inject cells
ploomber nb --inject

# now open any .Rmd files and execute them
```

More on that here: https://docs.ploomber.io/en/latest/user-guide/editors.html

Feel free to ask any questions and please submit any feedback you may have!
