### ISSUE TITLE
set params for all tasks

### ISSUE THREAD

**Issue by hornste** [ploomber/ploomber#513]
it would be helpful it would be possible to set global params for a pipeline, rather than hard code them to each specific task.

**Comment by edublancas** [comment]
Thanks for your feedback!

I'm thinking we could have a section like this:

```yaml
task_params:
    some_param: value

tasks:
   - source: a.py
      product: a.ipynb

   - source: b.py
      product: b.ipynb
```


Which would be equivalent to:

```yaml
tasks:
   - source: a.py
      product: a.ipynb
      params:
        some_param: value

   - source: b.py
      product: b.ipynb
      params:
        some_param: value
```

Thoughts?

**Comment by hornste** [comment]
Sure. That would work.

**Comment by eromoe** [comment]
@edublancas Can we make same variable in env.yml  global access in every task/script ?

**Comment by edublancas** [comment]
@eromoe can you provide an example of how the env.yaml and pipeline.yaml would look like?

**Comment by eromoe** [comment]
I mean

emv.yaml
```
basefreq: 1m
lbalabal: xxx
some: 1
```

Don't need declare, and all the variables can be access in all the tasks/scripts
```
  - source: scripts/pp_labeling.py
   # no need declare params
    product: 
      nb: products/pp_labeling.ipynb
      data: products/pp_labeling.pkl
```

This is much convenient for small or personal project.

**Comment by edublancas** [comment]
we haven't built global variables because they're not explicit: it's hard to know which task is using which variable. I think the `task_params` makes sense.

you can achieve something similar to what you want with environment variables (`os.environ`)

**Comment by edublancas** [comment]
relevant links:

https://github.com/ploomber/ploomber/pull/668
https://github.com/ploomber/ploomber/issues/648

**Comment by unnamedunknownusername** [comment]
First off, thanks so much for the hard work on this package, it really made my notebook code better.

I noticed the above PR's were closed.
was this functionality ever introduced?

I ask becasue I am wondering what the best way would be to "run a **WHOLE* pipeline" multiple times based on a different param found in the `env.yaml` file.

Maybe more concretely I have a pipeline
env.yaml
```
PARAM_YEAR = 2023
PARAM_YEAR = 2023
```


pipelin.yaml
```
  - source: tasks/task1SetUpInputs.ipynb
     params:
        INPUT_YEAR: PARAM_YEAR
    product: 
      nb: products/output1.ipynb
      data: products/output1.pkl

  - source: scripts/task2DoStuff
    product: 
      nb: products/output2.ipynb
      data: products/output2.pkl

  - source: scripts/task3GetFinalResult
    product: 
      nb: products/output3.ipynb
      data: products/output3.pkl
```

what I would like to do is run the whole pipeline for say PARAM_YEAR
