### ISSUE TITLE
Unable to use grid: with params: in pipeline.yaml

### ISSUE THREAD

**Issue by mat-ej** [ploomber/ploomber#522]
From tutorial:
`You can use params and grid in the same task. Values in params are constant across the grid.`

However when I try to define both grid and params I get the following error:
` 'params' is not allowed when using 'grid'"`
I define the task as follows:
```
    - source: tasks.fit.fit
      name: fit-
      upstream: [ 'features' ]
      product: products/fit.csv

      grid:
      - model: sklearn.ensemble.RandomForestClassifier
        n_estimators: [5, 10, 20]
        criterion: [gini, entropy]

      params:
        track: '{{track}}'
        mlflow_tracking_uri: '{{mlflow_tracking_uri}}'
```
