### ISSUE TITLE
Packaging components to re-use across teams

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#560]
We've had this come up a few times: teams using Ploomber want to provide functionality across the team. The typical case is database connectors but this extends to pre-built Python scripts, functions, SQL scripts, etc.

I imagine teams maintaining a package to share code, for example. Some teams may develop `team_package` in some repository, then users could install it with:

```
pip install git+https://git.organization.domain/team_package
```

Then, in a Ploomber pipeline:

```yaml
clients:
  # get db connector from the package so the user doesn't have to write their own logic
  SQLDump: team_package.db_client

tasks:
    # team provides a pre-built script task, example: download data from some remote source
  - source: team_package::download_data.py
    # user determines where to save it
    product: output/data.csv
    # user passes parameters to customize the task
    params:
      dataset_name: some_name

  # same applies for functions, the package may provide funcion-based tasks
   - source: team_package.module.function
      product: output/another-dataset.csv
```

The example above shows how a team could provide functionality that is abstracted from the user, they don't need to know the details, just the interface for the task (where's the source code, what are the parameters, and what outputs it generates).

There is a second use case: a team may want to provide templates: tasks that provide a starting point but where the user may want to modify the source code. For example, a team may provide a machine learning model template with cross-validation, some evaluation charts, some metrics, etc. So the user takes it as a starting point and modifies it to suit their needs. In such case, we could provide some functionality to copy the source code from `team_package` to the local folder:

```python
# this copies the template from the package to the current working directory
python -m team_package --copy machine_learning_template.py
```

Then the user can add it as a task to the pipeline:

```yaml
tasks:
   # note this uses the local copy, not the copy from team_package
   - source: machine_learning_template.py
      product: output/another-dataset.csv
```

Please share your feedback.
