### ISSUE TITLE
Support for python function tasks with decorators

### ISSUE THREAD

**Issue by benhowes** [ploomber/ploomber#569]
I wish to wrap tasks with a decorator in order to be able to pass in initialized client libraries/sessions.

e.g. I have a decorator `with_deployment_month_client` which uses a `deployment_uuid` and a `month` to create a client

In my pipeline:

```yaml
...
  - source: sq_data.loaders.load_subjects
    product: product/subjects.pickle
    params:
      deployment_uuid: '{{deployment_uuid}}'
      month: '{{month}}'
...
```

The ideal task code for me would be:
```python
@with_deployment_month_client
def load_subjects(product, client):
   pass
```

The current work around is to set the code as:
```python
@with_deployment_month_client
def load_subjects(product, deployment_uuid, month, client=None):
   pass
```
