### ISSUE TITLE
feature request: allow grid to span multiple notebooks

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#602]
Grid allows parametrizing a notebook to run multiple experiments with different parameters

```mermaid
  graph LR;
      prepare-->train-model-1;
      prepare-->train-model-2;
      prepare-->train-model-3;
```

However, in some cases, one may want to grid over many notebooks:

```mermaid
  graph LR;
      prepare-->train-model-1-->evaluate-model-1;
      prepare-->train-model-2-->evaluate-model-2;
      prepare-->train-model-3-->evaluate-model-3;
```

**Comment by williewheeler** [comment]
+1 to train vs evaluate.

In my case I'm looking to implement grid search that invokes feature engineering and selection, model training and model validation all as steps in the grid search. So I will need a way to push the hyperparams into the participating notebooks and also a way to roll up the search results into something that allows me to make a choice before say flushing out the hyperparams.

Also this may involve nested pipelines. What I mean is that I would expect the model search pipeline to invoke a separate model build pipeline, and ideally that's something that we could config in the pipeline.yaml.

**Comment by edublancas** [comment]
Hi @mat-ej , thanks for the feedback. Let me see if I understood it correctly.

Are you thinking of something like this?

```mermaid
  graph LR;
      prepare-->scikit-train--> scikit-evaluate;
      prepare-->pytorch-train-->pytorch-evaluate;
      prepare-->xgb-train-->xgb-evaluate;
```

So in this case, sikit-train, pytorch-train, and xgb-train are different scripts, right? But the *-evaluate notebooks are the same notebook except, it uses a different model as input to produce the evaluation report.

If so, it seems like we have two use cases.

1. Two notebooks that are repeated a few times, each pair receiving a different set of hyperparameters (this is the original diagram I posted)
2. X number of notebooks, followed by the same notebook. (this is the diagram I posted above)

Does this sound right?

**Comment by edublancas** [comment]
Hi,

I'll start working on this. Requesting some feedback. I'm thinking what's the cleanest API here, thinking of something like this:

```yaml
tasks:
   # to create a multi-notebook grid, pass a list
  - source: [model.py, evaluate.py]
    # product must have model and evaluate as keys
    product:
        model: output/model.html # this can be a dictionary, too
        evaluate: output/evaluate.html
   # this generates 3 * 2 = 6 tasks
    grid:
        n_estimators: [5, 10, 20]
        criterion: [gini, entropy]
```

The only question on my mind is how do we handle the parameters. For example, for the first task `n_estimators=5`, and `criterion=gini`, should we only pass them to the `model.py`, or also to `evaluate.py`?

To me, it seems like the `grid` params are only relevant to the first stage, but there might be circumstances where the other stages might want to know which parameters were used.

**Comment by edublancas** [comment]
Ok, so adding some more information to fully define the API. I think the typical use case for this will be creating a grid for a given task and then adding tasks before or after it. A typical use case will be: preprocessing -> training model -> evaluating a model.


```yaml
tasks:
   # to create a multi-notebook grid, pass a list
  - source: [preprocess.py, train.py, evaluate.py]
    # product should have all the task names as keys (preprocess, train, and evaluate)
    product:
        model: output/model.html # this can be a dictionary, too
        evaluate: output/evaluate.html
   # this generates 3 * 2 = 6 model tasks. since each one has its own preprocess and evaluate
   # then it has 6 * 3 = 18 tasks in total
    grid: # this should be a grid with a single key - and the value should be one of the task names
      model:
        n_estimators: [5, 10, 20]
        criterion: [gini, entropy]
    params: # this should be a dictionary with keys. the key in grid is not allowed here, and the others are optional
      preprocess:
         normalize: true
```

@94rain: this is a high effort feature so please open a draft PR, I'm happy to provide guidance. for starters, this is the code that parses the current grid implementation:

https://github.com/ploomber/ploomber/blob/2c79637129c9f32a1bb9996f16457136c5804efd/src/ploomber/spec/taskspec.py#L301
