### ISSUE TITLE
Better error message when incomplete pipeline.yaml

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#613]
A new user may try something like this:

```yaml
tasks:
  - source: something
     product: out
```

The error message isn't helpful. We should show them how to create a script/function task.

```
Error: Failed to determine task class for source 'something': Invalid dotted path 'something'. Value must be a dot separated string, with at least two parts: [module_name].[function_name].
```
