### ISSUE TITLE
are there way to version the pipelines and products?

### ISSUE THREAD

**Issue by arm2arm** [ploomber/ploomber#615]
hi, are there way to version the pipelines and products?
for example we have analysis.py (it could be a project/ folder): 
1)  git  tag v1 produces  datav1, 
2) git tag v2 produces datav2 and so on...
3) maybe we can convert analysis.py to pipeline:
and track versions easily?
how to move this workflow to ploomber, is it possible to track versions with ploomber infra?( the pipelines could be a scikit-learn pipelines)
more discussion is here: https://ploomber-io.slack.com/archives/C028KJCJDRT/p1645678474432339?thread_ts=1645678474.432339&cid=C028KJCJDRT

**Comment by edublancas** [comment]
Hi, thanks for your feedback.

This is possible, although it hasn't been documented yet. You can add a prefix to the products in the `pipeline.yaml` (to all or some of your tasks):

```yaml
tasks:
  - source: tasks.get
    product: '{{products}}/get.parquet'

  - source: tasks.features
    product: '{{products}}/features.parquet'

  - source: tasks.join
    product: '{{products}}/join.parquet'

  - source: fit.py
    name: fit
    product:
        nb: '{{products}}/nb.html'
        model: '{{products}}/model.pickle'
```

Then, tell Ploomber to set the prefix to the current git tag by adding an `env.yaml`

```yaml
# this _module key is required but it's a little weird - it's there due to some legacy implementation details
# I think it makes sense to make it optional
_module: .
products: '{{git}}'
```

Note that this requires annotated tags (`git tag v1 -m "some comment"`). Under the hood, Ploomber executes a `git describe` command.

Alternatively, you can use the CLI. So say you added the prefix to `pipeline.yaml`, then you can replace the prefix to any value you want, so to achieve the same effect:

```sh
ploomber build --env--products $(git describe)
```

I'll close this once we finish documenting this:

- [ ] add example
- [ ] link to example in the docs wherever relevant
- [ ] add a data versioning section in the docs
