### ISSUE TITLE
cookbook on managing multiple kernels

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#626]
Sometimes is useful to execute a given script/notebook with a specific kernel, so we should add a cookbook to show how to do this. These are some quick instructions, we need help moving this to the docs.

To list current kernels:

```
jupyter kernelspec list
```

The first column in the printed table shows the names, you can pass any of those to a script/notebook:

```yaml
  - source: fit.py
    product:
        nb: output/nb.html
        model: output/model.pickle
    kernelspec_name: some-kernel-name
```

In some situations, you may want to have an environment to execute `ploomber build` but have the kernel run on a different one. This is possible:

```
/path/to/kernel/env/bin/python -m ipykernel install --prefix=/path/to/jupyter/env --name 'python-my-env'
```
The first argument is the Python interpreter in an arbitrary environment, while the prefix is the one where `ploomber build` is called. To find the prefix value:

Activate the environment, then start Python, then:

```python
import sys
print(sys.prefix)
```

More info here: https://ipython.readthedocs.io/en/6.5.0/install/kernel_install.html#kernels-for-different-environments
