### ISSUE TITLE
Errors when loading a dict instead of the path

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#634]
When changing an upstream to have 2 outputs (on pipeline.yaml) but keeping the load for example for the path on a single parameter, it creates Nested folders. Instead it should output a warning to the user.

example:
From:
```
- source: get.py
    product: output/get.parquet
```
To:
```
- source: get.py
    product:
      nb: output/get.ipynb
      data: output/get.parquet
```

And not changing the task from:
```Path(str(product)).parent.mkdir(exist_ok=True, parents=True)```
To
```Path(str(product['data'])).parent.mkdir(exist_ok=True, parents=True)```

This will convert the whole dict as path and will create all of the dirs.
