### ISSUE TITLE
confusing error when passing something.html as source

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#646]
```yaml
  - source: fit.html
    product:
        nb: output/nb.ipynb
        model: output/model.pickle
```

```
(ploomber)  Edu@MBP Desktop/mlx » ploomber task fit0 -f
Loading pipeline...
Error: Failed to determine task class for source 'fit.html': list indices must be integers or slices, not str.
```

The issue is because `fit.html` is interpreted as a dotted path, hence Ploomber runs `import fit` and then tries to look for a function named `html`. However, since `fit.py` is a script, it contains this:

```python
# %% tags=["parameters"]
upstream = ['join']

# %%
df = pd.read_parquet(str(upstream['join'])) # breaks here since upstream is a list
```
