### ISSUE TITLE
Add option to customise names of grid tasks.

### ISSUE THREAD

**Issue by vgn1** [ploomber/ploomber#647]
When running tasks in a grid, a number is appended at the end of the tasks product names. For example, the following pipeline.yaml file:

```
- source: example_task.py
   name: example-task
   product:
       data: output/output_dataframe.csv
   grid:
       input_dataframe: ['birds.csv', 'fish.csv', 'flowers.csv']
```

would result in 3 products: output_dataframe-1.csv, output_dataframe-2.csv and output_dataframe-3.csv.

I would like to have an option to replace -1, -2 and -3 in the filenames with for example -birds, -fish and -flowers.

**Comment by edublancas** [comment]
Thanks for your feedback!

Any suggestions on how this could look like? I'm thinking of having a `product_prefix` like this:

```yaml
- source: example_task.py
   name: example-task
   product:
       data: output/output_dataframe.csv
   grid:
       input_dataframe: ['birds.csv', 'fish.csv', 'flowers.csv']
   product_suffix: '_{{input_dataframe}}
```

Then, the outputs would be 'output/output_dataframe_birds.csv', etc.

**Comment by vgn1** [comment]
Yes! Something like that would be great.

I forgot this in the original issue description, but I think the suffix also should be (optionally) added to the task name. So that the name can be the same as the products.

**Comment by hornste** [comment]
I like the product_suffix as well. Would be nice to apply to task_suffix as well.

That way if you had something like:

```
grid:
   param1: [1,2,3,4]
   param2: [a,b,c,d]
```

you could do, product_suffix: '-{{param1}}-{{param2}}'

**Comment by edublancas** [comment]
Hi all,

I started working on this. Bouncing off an idea.

To have a more flexible naming logic, I was thinking something like this:

```yaml
- source: example_task.py
   name: example-task
   product:
       data: output/[[input_dataframe]]
   grid:
       input_dataframe: ['birds.csv', 'fish.csv', 'flowers.csv']
```

This would output: `output/birds.csv`, etc. Having the placeholders anywhere in the product path will allow you to organize them by folder and is a lot more customizable (the initial Idea I had with the `product_suffix` is kind of limited)

Note that this would use a special `[[placeholder]]` notation to prevent clashing with the regular `{{placeholder}}` notation from the `env.yaml`.

Thoughts?
