### ISSUE TITLE
Setting task class default init parameters

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#648]
(note that this is related to #513)

In some cases, we want to customize how a task is initialized, for example, if we want to hide the code in an output HTML report, we can create a task like this:

```yaml
tasks:
  - source: fit.py
    product:
        nb: output/nb.html
        model: output/model.pickle
    
    # hide code
    nbconvert_export_kwargs:
      exclude_input: True
```

However, if we have multiple tasks, and want to hide the code in all the outputs, we need to pass the initialization parameters to all of them, which is too verbose. Alternatively, we can provide a way to pass default initialization parameters:

```yaml
init_defaults:
    # passes to all tasks
    Task:
        params: {a: 1}
    # passes to all notebook tasks
    NotebookRunner:
        nbconvert_export_kwargs:
            exclude_input: True
```

Notes

* this conflicts with `clients`, perhaps throw an error if clients appears here and tell the user to pass them in the clients section
* do not allow certain arguments. For example all __init__ methods take a dag argument but that should be allowed here
* this requires knowledge of the names of the underlying classes. is there any way to make this simpler?

**Comment by idomic** [comment]
@jramirez857 want to take a look?

**Comment by jramirez857** [comment]
> @jramirez857 want to take a look?

Yes, I'll try this out

**Comment by jramirez857** [comment]
Hi, @edublancas @idomic . I have a couple questions

1. Am I correct in understanding the yaml file would look something like this?

```YAML
init_defaults:
    # passes to all tasks
    Task:
        params: {a: 1}
    # passes to all notebook tasks
    NotebookRunner:
        nbconvert_export_kwargs:
            exclude_input: True
        static_analysis: regular
    SQLUpload:
        chunksize : 20000
tasks:
  - source: fit.py
    product:
        nb: output/nb.html
        model: output/model.pickle
    
```

2. If the init_defaults section is new to the YAML, which other parts of the codebase would this affect (e.g. DAG or loader)? 
3. Would this only encompass parameters in tasks.py, sql.py and aws.py classes? 

I appreciate your help as I am familiarizing myself with the codebase!
