### ISSUE TITLE
Allow task parameter to be used as variable within task

### ISSUE THREAD

**Issue by hornste** [ploomber/ploomber#653]
It would be nice if one could use a task parameter. This might be somewhat solved with issue Add option to customise names of grid tasks. #647 , but I would expect that I could use the parameters in this way.

for example:

tasks:
     - source: ...
     name: ....
     params: 
          param1: 'test'
     product:
          nb: output/{{param1}}.ipynb
          csv: products/{{param1}}.csv
          json: products/{{param1}}.json
         etc.

**Comment by chris-aeviator** [comment]
I'm doing this all the time, check ENV variables for this

**Comment by edublancas** [comment]
this can be done with an `env.yaml`:

```yaml
# env.yaml
param1: test
```

then the `pipeline.yaml`

```yaml
tasks:
     - source: ...
     name: ....
     params: 
          param1: '{{param1}}'
     product:
          nb: output/{{param1}}.ipynb
          csv: products/{{param1}}.csv
          json: products/{{param1}}.json
         etc.
```

I'm keeping this open anyway in case we work on it
