### ISSUE TITLE
How to hide generated code cells?

### ISSUE THREAD

**Issue by WolfgangFahl** [ploomber/ploomber#658]
Ploomber generates two "internal" code blocks when generating notebooks from python notation which are unfortunately visible by default:

<img width="302" alt="grafik" src="https://user-images.githubusercontent.com/1336221/158992552-005a9d54-1ef8-4c49-bc65-61ed7a1da8f5.png">

Trying to make these invisible i found:

- https://stackoverflow.com/questions/31517194/how-to-hide-one-specific-cell-input-or-output-in-ipython-notebook
- https://stackoverflow.com/questions/27934885/how-to-hide-code-from-cells-in-ipython-notebook-visualized-with-nbviewer
- https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/hide_input/readme.html
- https://stackoverflow.com/questions/34818723/export-notebook-to-pdf-without-code
- https://github.com/jupyter/notebook/issues/534 

Literally millions of clicks have been invested into the cell hidding issue in the last 7 years which is amazing.
**What would be a current workaround  to make the cells invisible** especially when converting to output such as html,pdf or latex? 
H**ow is this going to be handled once version 7 is out** and https://github.com/jupyter/notebook/issues/534 
 hopefully closed?

**Comment by edublancas** [comment]
Hi, thanks for your feedback!

You can hide all code cells when converting to HTML, pdf by passing this to the task:

```yaml
    # optional config to hide the code in the output/nb.html report
    nbconvert_export_kwargs:
      exclude_input: True
```

Here's an [example](https://github.com/ploomber/projects/blob/master/templates/ml-basic/pipeline.yaml)

Does this solve the issue?

**Comment by WolfgangFahl** [comment]
@edublancas  - thanks for the swift answer.
**Does this solve the issue?**
No - it does not - i specifically want to hide the cells introduced by ploomber not the regular ones that are part of our solution. As you can see from the long list of links above and all the hits these links got i was assuming this is a well known issue by now.

The other problem is that the option seems to have no effect in my environment. I am using
```
jupyter nbconvert --to pdfviahtml 
```
since i also have generated html in my jupyter notebooks and the regular 
```
jupyter nbconvert --to pdf
```
takes a complicated route via tex while the pdfviahtml cleverly seemly takes the browser content. So it's the browser content i'd like to modify. Quite a few hint say this should be possible with "remove_cell" "hide-cell", "hide_cell", "hide_input", "hide-input" tags and what not. Not a single suggestion i have seen has had the desired effect so far. This all seems to be strangely obscure for a relatively clear need to hide some code that is just there for technical reasons and does not have a purpose for the content to be displayed in the jupyter notebook.

**Comment by edublancas** [comment]
got it! Yeah, you can achieve that, that's actually a feature from the `nbconvert` package but you can pass the arguments via ploomber to achieve that result:

```sh
 ploomber examples -n templates/ml-basic -o example
cd example
```

Edit the `pipeline.yaml` so it looks like this:

```yaml
tasks:
    # tasks.get, features and join are python functions
  - source: tasks.get
    product: output/get.parquet

  - source: tasks.features
    product: output/features.parquet

  - source: tasks.join
    product: output/join.parquet

    # fit.py is a script (that you can open as notebook in Jupyter)
  - source: fit.py
    name: fit
    product:
        nb: output/nb.html
        model: output/model.pickle

    # hide cells with the tag "injected-parameters"
    nbconvert_export_kwargs:
      config:
        HTMLExporter:
          preprocessors: [nbconvert.preprocessors.TagRemovePreprocessor]
        TagRemovePreprocessor:
          remove_cell_tags: [injected-parameters]
```

Then build:

```
ploomber build
```

You'll see that `output/nb.html` does not contain the injected parameters, here's my output, you can see that there is no cell numbered as 3 because the post-processor deleted it:

![Screen Shot 2022-03-21 at 22 03 18](https://user-images.githubusercontent.com/989250/159405700-3fbe8d70-b4f4-462b-9248-ac7708158b9e.png)

You can customize this to hide other cells as well.

**Comment by WolfgangFahl** [comment]
Your analysis is very helpful and i am making progress. I am now using a shells script to generate my pipeline files:
```bash
#!/bin/bash
# ploomber build
# WF 2022-03-17
force="false"
pipeline="false"

#
# create a pipeline.yaml as per
# https://github.com/ploomber/ploomber/issues/658
#
# params
#  #1 Exercise number
#  #2 tag to complete remove
#  #3 tag to remove input
#
createPipeline() {
  local l_ubno="$1"
  local l_remove_tag="$2"
  local l_removeinput_tag="$3"
cat << EOF > pipeline.yaml
# this task was generated by the build script
# if you modify it manually it might get overridden on the next run
# of the build script
tasks:
- source: UB-${l_ubno}.py
  name: UB-${l_ubno} Jupyter notebook generation
  static_analysis: disable
  product:
    nb: UB-${l_ubno}.ipynb

- source: UB-${l_ubno}.py
  name: UB-${l_ubno} html generation
  static_analysis: disable
  product:
    nb: UB-${l_ubno}.html

  # hide cells with the tag "$l_hidetag"
  nbconvert_export_kwargs:
      config:
        HTMLExporter:
          preprocessors: [nbconvert.preprocessors.TagRemovePreprocessor]
        TagRemovePreprocessor:
          remove_cell_tags: [$l_remove_tag]
          remove_input_tags: [$l_removeinput_tag]
EOF
}
while [  "$1" != ""  ]
do
  option="$1"
  shift
  case $option in
    -f|--force)
      force="true"
    ;;
    -p|--pipeline)
      pipeline="true"
    ;;
    *)
      ub=$option
      cd ub-$ub
      if [ "$force" == "true" ]
      then
        rm UB-$ub.ipynb
        rm UB-$ub.html
      fi
      if [ "$pipeline" == "true" ]
      then
        createPipeline $ub injected-parameters remove_input
      fi
      ploomber build
  esac
done
```
when i run the build script the html and jupyter notebook is generated and the handling of the tags injected-parameters and remove_input seems to work. 
An example pipeline.yaml file is:
```yaml
# this task was generated by the build script
# if you modify it manually it might get overridden on the next run
# of the build script
tasks:
- source: UB-2.py
  name: UB-2 Jupyter notebook generation
  static_analysis: disable
  product:
    nb: UB-2.ipynb

- source: UB-2.py
  name: UB-2 html generation
  static_analysis: disable
  product:
    nb: UB-2.html

  # hide cells with the tag ""
  nbconvert_export_kwargs:
      config:
        HTMLExporter:
          preprocessors: [nbconvert.preprocessors.TagRemovePreprocessor]
        TagRemovePreprocessor:
          remove_cell_tags: [injected-parameters]
          remove_input_tags: [remove_input]
```

this is the result on the command line:
```bash
./build -f -p 2
rm: UB-2.ipynb: No such file or directory
Loading pipeline...
Black is not installed, parameters wont be formatted
Black is not installed, parameters wont be formatted
Executing: 100%|██████████████████████████| 21/21 [00:02<00:00,  7.25cell/s]
Executing: 100%|██████████████████████████| 21/21 [00:02<00:00,  7.50cell/s]
Building task 'UB-2 html generation': 100%|███| 2/2 [00:06<00:00,  3.01s/it]
name                              Ran?      Elapsed (s)    Percentage
--------------------------------  ------  -------------  ------------
UB-2 Jupyter notebook generation  True          2.93825       48.9296
UB-2 html generation              True          3.06681       51.0704
````

A strange side effect is that the jupyter notebook is immediately removed after a few seconds. 
**How can i avoid that removal of the notebook just generated?**

 Another aspect is that i still don't know how to generate the pdf as i'd do with the command line:
```bash
jupyter nbconvert --to pdfviahtml
```
**How would the pdfviahtml conversion be started from the pipeline using the same tag preprocessing parameters?**

**Comment by idomic** [comment]
Did you check the script isn't removing them? (maybe in the while loop)
I think more context on the use case and what we're trying to achieve will be helpful here.
For the conversion you can use something like: `nbconvert.exporters.pdf.PDFExporter` in a similar manner.
`PDFExporter:
          preprocessors: [nbconvert.preprocessors.TagRemovePreprocessor]`

**Comment by WolfgangFahl** [comment]
@idomic 
I am now calling the tasks by name and the removal seems to be part of the html generation part as an unwanted side effect. 
```yaml
# this pipeline was generated by the build script
# if you modify it manually it might get overridden on the next run
# of the build script
tasks:
- source: UB-0.py
  name: UB-0-gen-nb
  static_analysis: disable
  product:
    nb: UB-0.ipynb

- source: UB-0.py
  name: UB-0-gen-html
  static_analysis: disable
  product:
    nb: UB-0.html

  # hide cells with the tag ""
  nbconvert_export_kwargs:
      config:
        HTMLExporter:
          preprocessors: [nbconvert.preprocessors.TagRemovePreprocessor]
        TagRemovePreprocessor:
          remove_cell_tags: [injected-parameters]
          remove_input_tags: [remove_input]
```
the work around is currently to change the order of tasks running and regenerated the notebook after it was removed
```bash
 # first generate html (will remove notebook while doing so)
      ploomber task UB-$ub-gen-html -f
      # regenerate notebook as workaround
      ploomber task UB-$ub-gen-nb -f
```

As for your PDFExporter hint - i don't know how apply that in a pipeline. I am just not familiar with the syntax and options yet so how would the PDF export look as part of pipeline.yaml file?
