### ISSUE TITLE
Multiple nb products

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#673]
Currently the nb product is limited to a single file.
It'll be useful for users to output multiple reports for instance:
```
- source: fit.py
    product:
        nb: output/nb.ipynb    
        html-report: output/report.html    
```
