### ISSUE TITLE
support for alternative notebook PDF converters (e.g. webpdf)

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#675]
(see #672 and #658 for context)

There are a few engines to convert `.ipynb` to `.pdf`, however, we only support the default one provided by nbconvert, which depends on pandoc and text. It has a few downsides such as not being able to render embedded charts (see #658), we should add support for other engines

**Comment by neelasha23** [comment]
Can I work on this issue?

**Comment by idomic** [comment]
Go ahead! Thank you for contributing and reach out if you have any issues.

**Comment by edublancas** [comment]
A few pointers:

[This is the implementation](https://github.com/ploomber/ploomber/blob/a766bef90fff5fb5da6431af3e823c46d3da66f0/src/ploomber/tasks/notebook.py#L400) of the task that runs scripts. the `nbconvert_exporter_name` can switch to `webpdf`

[And this is where](https://github.com/ploomber/ploomber/blob/a766bef90fff5fb5da6431af3e823c46d3da66f0/src/ploomber/tasks/notebook.py#L91) the notebook conversion logic happens - we rely on nbconvert for format conversion so please check the docs.

Parameters from the `pipeline.yaml` are passed to the `NotebookConverter`. 
 example:

```yaml
  - source: fit.py
    nbconvert_exporter_name: webpdf
    name: fit
    product:
        model: output/model.pickle
        nb: output/report.pdf
```

If you try this, it'll fail and ask you to run `pip install nbconvert[webpdf]`, that's ok, the user can install it once they see the message.

If you try again, it'll complain that chromium is missing. The exporter has an option to automatically download it so we need to ensure that when we instantiate the `webpdf` exporter,  we set that to true. So you'll need to dig into [nbconvert](https://github.com/jupyter/nbconvert/blob/main/nbconvert/exporters/webpdf.py)'s docs/surce code

**Comment by neelasha23** [comment]
@edublancas Thanks a lot for the pointers!

**Comment by edublancas** [comment]
closing this. thanks to @neelasha23 for putting this together!

I'll create a new section in the docs to show this and a few extra things, for the moment being, this is how to use webpdf:

```yaml
  - source: scripts/fit.py
    product:
      nb: products/report.pdf
    nbconvert_exporter_name: webpdf  
```

This will download chromium if needed, note that this requires: `pip install "nbconvert[webpdf]"`
