### ISSUE TITLE
cookbook: reusing tasks

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#680]
we've been getting the question of re-using tasks a few times now, this is possible turning `extract_upstream` off, we should add a cookbook:

```yaml
# pipeline.yaml
meta:
  extract_upstream: false

tasks:
  - source: task.py
    name: task-a
    products: ...
    upstream [another]

  - source: task.py
    name: task-b
    products: ...
    upstream [a-different-one]
```
