### ISSUE TITLE
Re-using tasks

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#682]
(This issue discusses a few approaches for re-using tasks. The objective is to open the discussion to add a new example that showcases this)

## Re-using tasks in different `pipeline.yaml` files via `import_tasks_from`

This directive allows composing pipelines. [Typically used](https://docs.ploomber.io/en/latest/deployment/batch.html#composing-batch-pipelines) for composing training and serving pipelines. This is a good approach when the same task needs to appear in two separate `pipeline.yaml`

## Re-using the same `source:` in the same `pipeline.yaml`

Another use case is re-using the same task in the same `pipeline.yaml`. For example, let's say we have a `tasks.drop_columns` task that we want to apply to different datasets. By default Ploomber ties the tasks to their upstream since the names of the upstream tasks must appear in the source. Example:

```python
# tasks.py
def drop_columns(upstream, product):
    df = pd.read_csv(upstream['train'])
    # ...
```

To fix this, we can turn off `extract_upstream`:

```yaml
meta:
    extract_upstream: false

tasks:
    - source: tasks.train
      ...

    - source: tasks.drop_columns
      name: drop-columns-from-train
      upstream: [train]
      ...

    - source: tasks.test
      ...

    - source: tasks.drop_columns
      name: drop-columns-from-test
      upstream: [test]
```

Then, in our `tasks.py`:

```python
# tasks.py
def drop_columns(upstream, product):
    name = list(upstream)[0]
    df = pd.read_csv(upstream[name])
    # ...
```

Note that this new version doesn't refer to the upstream by name, since in one case, the upstream will be `train` and in the second, it will be `test`). Alternatively, we could the shortcut: `upstream.first`, which will return the product of the upstream dependency, regardless of what the name of the upstream task is.

[Here's an example](https://github.com/ploomber/projects/blob/reuse-tasks/cookbook/reuse-tasks/parallel-branches/pipeline.yaml)

This gets a bit trickier if the upstream products come in different shapes (e.g. one generates a single product `output.csv`, but another one generates multiple: `{'train': 'train.csv', 'test': 'test.csv'}`). In such case, the task can be parametrized to know which upstream product to use.

```yaml
    - source: tasks.drop_columns
      name: drop-columns-from-test
      upstream: [split_data]
      params:
        # process the "train" product generated by the "split_data" upstream task
        product_key: train
```

[Here's an example](https://github.com/ploomber/projects/blob/reuse-tasks/cookbook/reuse-tasks/tree/pipeline.yaml)

Alternatively, @fferegrino suggested that a task may declare a specific product as upstream (as opposed to a task). However, this requires a good amount of work since the current implementation only allows to establish "upstream/downstream" relationships among tasks.
