### ISSUE TITLE
Ploomber <> Dash app compatibility?

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/ploomber#685]
Hi!
 Was wondering if there is openness to incorporate Dash dashboards as a potential product?

Use case:
Given a series of .py scripts for data download, processing and visualizing, I'd like for one of them to contain a Dash app (see examples https://github.com/plotly/dash-sample-apps), such that when I deploy a Ploomber pipeline, it launches a local server with the app. 

Ideally, the first few scripts in the pipeline are focused on obtaining, cleaning and modelling the data, and the app is focused solely on building a Python-in-the-backend app for visualizing and interacting with results. 

More about Dash (Python) 

https://dash.plotly.com/reference 

Jupyter + Dash

https://github.com/plotly/jupyter-dash

**Comment by edublancas** [comment]
Hi, thanks for the feedback!

I like the idea of automating the full process. I believe it's best to keep the ploomber pipeline and dash app separate since ploomber expects pipelines to run and finish, while dash is a long-lived server process. However, I still think there's room to have good integration between the two.

How is input data fed into a Dash app? I'm guessing you're passing a path to the file with clean data?

**Comment by lfunderburk** [comment]
> How is input data fed into a Dash app? I'm guessing you're passing a path to the file with clean data?

Yes, you can pretty much build functions you need to read the data (dataframe through a Pickle, CSV, TSV, Excel, etc...) as you would with your visualization with Jupyter, or an IDE. 

The Dash app machinery is separate from this.

**Comment by edublancas** [comment]
Ok, so I think this is a good use case for a [cookbook](https://github.com/ploomber/projects/tree/master/cookbook).

Here's the idea: a ploomber pipeline that loads raw data and processes it. now, say you want to feed your Dash app with the output of the `clean` task:

```yaml
# pipeline.yaml

tasks:
  # ... more tasks here
  
  # this is the task that produces the data that dash will use, but this can be many files or even many tasks
  - source: scripts/clean.py
     products:
       nb: output/clean.html
       # we want to use this as input data in Dash
       data: output/clean.csv
```

Then, in your dash app (let's call it `app.py`), you can use Ploomber's Python API to connect the pipeline to the app:

```python
# app.py
import pandas as pd
from ploomber.spec import DAGSpec

dag = DAGSpec('pipeline.yaml').to_dag()

clean = pd.read_csv(dag['clean'].products['data'])
# there could be more data loading lines here...
```

The setup above creates a much cleaner and more flexible environment, since you are not hardcoding any paths in your `app.py`, furthermore, if you parametrize your ploomber pipeline, you could see how that changes your dash app. example:

```sh
# switch parameter from env.yaml - this will produce a different clean dataset
ploomber build --env--some-parameter 10

# deploy app, see how it looks like with the new clean dataset
python app.py
```

Thoughts? If you find some time, you can contribute with this cookbook :)
