### ISSUE TITLE
Support variables in env.yaml

### ISSUE THREAD

**Issue by williewheeler-ms** [ploomber/ploomber#696]
Compare:

```
data_out_dir = "../output/data"
models_out_dir = "../output/models"
alerts_out_dir = "../output/alerts"
```

vs.

```
out_dir = "../output"
data_out_dir = "{{out_dir}}/data"
models_out_dir = "{{out_dir}}/models"
alerts_out_dir = "{{out_dir}}/alerts"
```

**Comment by edublancas** [comment]
Interesting, are you thinking of something flexible?

```yaml
a: value
b: '{{a}}/something'
c: '{{b}}/another'
```

Or have a separate section:

```yaml
variables:
    a: value

b: '{{a}}/something'
c: '{{a}}/something/another'
```

The first one is succinct, but for large `env.yaml` files - it might get a bit hard to read. The second one is more strict, but the structure is clear. Thoughts?
