### ISSUE TITLE
Path resolution discrepancy between ploomber build and Jupyter integration

### ISSUE THREAD

**Issue by williewheeler-ms** [ploomber/ploomber#697]
### Summary

Ploomber resolves relative paths differently depending on the context. In `ploomber --build` it seems that the paths are resolved relative to the current working directory. In Jupyter, they are resolved relative to the notebook location. The result is that the notebooks can't find files in one or the other context.

### Background

I'm using `pipeline.yaml` to inject relative paths into the notebooks in the standard way:

```
  - source: '{{src_nb_dir}}/change-point.py'
    name: change-point
    product: '{{out_nb_dir}}/change-point.ipynb'
    params:
      data_path: '{{out_data_dir}}/request-latencies.parquet'
```

In `env.yaml` I have

```
out_data_dir: '../output/data'
```

Relevant directory structure:

```
D:\SOURCE\REPOS\SPOPERFMODELINGANDANALYSIS\REGRESSIONDETECTION
├───output
│   ├───data
│   └───nb
├───pipeline
    └───.ipynb_checkpoints
```

My notebooks are in `pipeline`.

So in the above, the notebooks find the data files in Jupyter, but not in `ploomber build`.
