### ISSUE TITLE
Discovering features

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#751]
Users are having a hard time finding some of our features. Adding Algolia to the docs helps with discovery but we can do more. I think we should make suggestions to the users so they can learn constantly. To keep it simple, we can define some heuristics.

For example, if a user is using the same source many times, we can suggest using `grid`.

```yaml
tasks:
  - source: fit.py
     name: fit-a
     params:
       a: 10

  - source: fit.py
     name: fit-b
     params:
       a: 20
```

We can embed this as part of the running process. For example, user runs:

```
ploomber build
```

After we print the execution status, we can print:

```
We noticed you're using the same source multiple times. Check out grid to simplify your workflow: [link to docs]
```

Another variation can be: passing the same parameters to many tasks (with different sources), in such case. we'd suggest declaring them in the defaults section (PR still WIP)
