### ISSUE TITLE
composing pipelines from multiple pipeline.yaml

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#761]
it's often useful to break a data analysis pipeline into multiple parts. one use case is when a large team works on the same analysis but it's divided into sub-teams that only work with certain parts of it. Note that this is different from the `import_tasks_from` use case since in that case, we want to re-use logic in multiple pipelines.

Currently, we can implement pipeline composition "manually": we may have a `pipeline.first.yaml` workflow that produces some final output (say, `clean-data.parquet`), and have a second `pipeline.second.yaml` workflow read `clean-data.parquet`.

```yaml
# pipeline.first.yaml
tasks:
  # some tasks...

  - source: scripts/final.py
    product: output/clean-data.parquet
```

```yaml
# pipeline.second.yaml
tasks:
  - source: scripts/start.py
     product: output/another.parquet
     params:
         input_path: output/clean-data.parquet

  # more tasks...

```

While this works, it's sub-optimal. We should have a user guide to show how to implement this with existing features:

* use an `env.yaml` to prevent hardcoding the path to the file
* use `resources_` to ensure that changes to the products trigger a downstream execution

Note that `resources_` is only designed to work with small files, so improving the experience here would imply developing a new feature. off the top of my head, there are a few things we could do to improve performance when using `resources_`:

* use the filesize as a first trial to check if a file has changed (faster than hashing)
* leveraging the existing `.metadata` file (e.g. if any of the `param`s in a task "looks like a path" and has a `.metadata` file, we could hash the metadata instead of the file
