### ISSUE TITLE
Make ploomber build write parameters on source code as well

### ISSUE THREAD

**Issue by tomaz-suller** [ploomber/ploomber#789]
I've just installed `ploomber` to use in a simple personal project, but I've struggled with how the pipeline configuration in `pipeline.yaml` forces the user to leave some of the parameters in the YAML file and others in the script itself if the user wants the scripts to run manually, without using `ploomber`. I believe if `ploomber build` or some other command in the CLI also injected the parameters into the source code, this would not be an issue.

The use case I've imagined is this: a user wants to centralise all their parameters on the `pipeline.yaml` file so that they don't need to look for parameters in each of their source files, yet they also want the option to run their source code manually, without using `ploomber`. Currently, it seems to me this is not possible, and a concrete example from the templates highlights this: it is not possible to run the [`clean.py`](https://github.com/ploomber/projects/blob/de47cf98cc6b4cc14117924b623ded989ab870d7/templates/exploratory-analysis/scripts/clean.py) script from the `exploratory-analysis` template by itself, since the parameters tag states that `product = None` and `ploomber` does not inject the parameters back into the source code when running `ploomber build` or any other command. Ideally, you'd have another command in the CLI such as `ploomber sync` that would take the parameters from `pipeline.yaml` and write them back to the source code.

The same problem is also present when using functions as source, though I can't think of any way for allowing scripts to be executed by themselves that would make sense -- just running e.g `python script.py` feels weird. Also I'm not sure about notebooks in the `.ipynb` format, because the videos I've seen seem to imply the parameter cells are added to them, though only when editing on Jupyter?

**Comment by tomaz-suller** [comment]
Thanks for the quick reply @edublancas .

First, on your suggestion. I'm actually getting some weird behaviour when executing `ploomber nb --inject`. The relevant portion of my `pipeline.yaml` is
```yaml
meta:
  extract_upstream: False
  extract_product: False
  product_relative_to_source: True
executor: parallel

tasks:

  - source: "1_1-Parse forms.py" # Notebook in py:percent format
    upstream: null
    product:
      nb: "1_1-Parse forms.ipynb"
      enem_dir: ../data/2_intermediate/forms/example
      fuvest_dir: ../data/2_intermediate/forms/fuvest

  - source: "1_2-Parse essays.py" # Notebook in py:percent format
    upstream: null
    product:
      nb: "1_2-Parse forms.ipynb"
      enem_dir: ../data/3_intermediate/redacoes/enem
      fuvest_dir: ../data/3_intermediate/redacoes/fuvest
      enem_manual_review_dir: ../data/2_intermediate/redacoes/enem
      fuvest_manual_review_dir: ../data/2_intermediate/redacoes/fuvest
```
When I inject the parameter cell, I get this output from the terminal:
```zsh
$ ploomber nb --inject
Loading pipeline...
Black is not installed, parameters wont be formatted
Black is not installed, parameters wont be formatted
Error: 'prefix'
```

I also get different results for each of the source files in these tasks. In `1_1-Parse forms.py` I get
```python
# %% tags=["parameters"]

# %% tags=["injected-parameters"]
# Parameters
product = {"nb": "/mnt/ubuntu_home/tomaz/git/MDV/new/src/1_1-Parse forms.ipynb", "enem_dir": "/mnt/ubuntu_home/tomaz/git/MDV/new/data/2_intermediate/forms/example", "fuvest_dir": "/mnt/ubuntu_home/tomaz/git/MDV/new/data/2_intermediate/forms/fuvest"}
```
which has the injected parameters just like I wanted, but in `1_2-Parse essays.py` I only get an empty parameter cell
```python
# %% tags=["parameters"]

```
I'm not sure if I've configured something wrong or if I've found a bug in this feature.

Now into your questions:
* The use case I envision is someone working on a `.py` file in `py:percent` notebook format who wants to run the notebook interactively during development, and later wants to create a `ploomber` pipeline from these notebooks. Furthermore, this person wants to centralise all their parameters on the `pipeline.yaml` file to avoid having to edit parameters in each of their scripts individually. This (you could say rather narrow but still existent) use case should indeed be supported if `ploomber nb --inject` was working correctly. Admittedly, you could work on `.ipynb` instead of `.py` during interactive work, but you then have a problem with versioning the notebooks (which I've highlighted in [an issue in the `jupytext` repository](https://github.com/mwouts/jupytext/issues/871#issuecomment-1128981950)).
* I didn't use the search bar, to be honest I didn't even see it there. I've searched now for "parameter" and "tags parameter" and found some useful posts, though nothing on the `ploomber nb --inject` command.
