### ISSUE TITLE
improvements to cloud task resources

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#812]
implement some default values:

```yaml
task_resources:
  __default:
    vcpus: 4
    memory: 8192
    gpu: 1
```

and wildcard:

```yaml
task_resources:
  fit-__:
    vcpus: 4
    memory: 8192
    gpu: 1%
```
