### ISSUE TITLE
validate task resources locally

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#813]
validate the content of task resources before pushing it to the cloud. Example, if there isn't a task with name `some-name`, the following should throw an error before uploading the code

```yaml
task_resources:
  some-name:
    vcpus: 4
    memory: 8192
    gpu: 1
```
