### ISSUE TITLE
Shell script task with multiple products

### ISSUE THREAD

**Issue by reesehopkins** [ploomber/ploomber#859]
I get the following error 

```
Error: Failed to initialize task 'clean'
'Getitem' object has no attribute 'name'
```

when running the pipeline

### pipeline.yaml

```yaml
tasks:
  - source: get_data.py
    product:
      nb: get_data.ipynb
      data: data.csv
  
  - source: clean.sh
    product: output.log
```

### get_data.py

```python
import numpy as np
import pandas as pd

# + tags=['parameters']
upstream = None
product = None
# -

data = pd.DataFrame(
    {"A": np.random.randint(0, 10, 10), "B": np.random.randint(10, 20, 10)}
)
data.to_csv(product["data"])

```

### clean.sh

```sh
echo "Starting" >> {{product}}
cat {{upstream['get_data']['data']}}
```

I tried to follow these [docs](https://docs.ploomber.io/en/latest/user-guide/shell.html#shell-tasks), but there wasn't an example using a shell script downstream of a Python script. FWIW, I found a work around by hard-coding my file paths into my shell script.
