### ISSUE TITLE
Error when pipeline.yaml file has indentation issue

### ISSUE THREAD

**Issue by neelasha23** [ploomber/ploomber#872]
Pipeline.yaml had some indentation inconsistency in one of the entries, however the error that came up was related to placeholders:
```
ploomber.exceptions.DAGSpecInitializationError: Failed to initialize spec. It looks like you're using placeholders (i.e. {{placeholder}}). Make sure values are enclosed in parentheses (e.g. key: "{{placeholder}}"). Original parser error:
                  
                  mapping values are not allowed here
                     in "<unicode string>", line 14, column 11:
                             name: clean
```

**Comment by edublancas** [comment]
do remember the `pipeline.yaml` contents so we can reproduce it?

**Comment by neelasha23** [comment]
Yes it was something like:

```
meta:
  extract_product: False

tasks:
  - source: raw.py
    name: raw
    product: {'nb': '{{path.products}}/data.ipynb', 'data': '{{path.products}}/data.csv'}

  - source: clean_one.py
     name: clean-1
     product: {'nb': '{{path.products}}/clean_one.ipynb', 'data': '{{path.products}}/clean_one.csv'}

  - source: clean_two.py
    name: clean-2
    product: { 'nb': '{{path.products}}/clean_two.ipynb', 'data': '{{path.products}}/clean_two.csv' }

  - source: plot.py
    name: plot
    product: {'nb': '{{path.products}}/plot.ipynb'}
```

If we validate this on a yaml validator the error is `(<unknown>): mapping values are not allowed in this context at line 10 column 10`. So maybe if this error comes up we can throw error `Possible indentation issue`
