### ISSUE TITLE
Ignoring non-notebook tasks in Jupyter manager to prevent loading problems

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#879]
DAGMapping currently creates a map of all tasks but it should only do so for notebook/script tasks. e.g., ignore tasks whose source is a function or a SQL script:

Essentially we want to move the `pairs` iteration logic inside the `DAGMapping` constructor:

https://github.com/ploomber/ploomber/blob/c87c60db954f72309b1e421a5399f9f6a426e5fe/src/ploomber/jupyter/manager.py#L185

then add a condition to such iteration logic to ignore tasks if they're not of the `ploomber.tasks.NotebookRunner` class.

This will allow us to prevent problems like this: https://github.com/ploomber/ploomber/issues/878

To test it, we can create a pipeline with a function task and a notebook task:

```yaml
tasks:
  - source: module.function
     product: output.txt
   
   - source: notebook.ipynb
      product: out.html 
```

we should create notebook.ipynb but do not create module.function, then we should check that if we open notebook.ipynb in jupyter, the cell is injected
