### ISSUE TITLE
Allowing to switch start_method in Parallel executor

### ISSUE THREAD

**Issue by lambdaofgod** [ploomber/ploomber#882]
I have some Pytorch code which I want to run on GPU (`net.cuda()` and whatnot)

I get the following error:
```
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```
I tried to fix this by either calling
```
mp.set_start_method('spawn', force=True)
```

or 
```
torch.multiprocessing.set_start_method('spawn')
```

In the first case nothing happens, and in the second I get `RuntimeError: context has already been set`

How to set multiprocessing start method with ploomber?

**Comment by edublancas** [comment]
By default, Ploomber executes tasks in a sub process. Looks like that's causing trouble. You can deactivate that by adding this at the top of the pipeline.yaml

```yaml

executor:
  dotted_path: ploomber.executors.Serial
  build_in_subprocess: false # do not run function tasks in a subprocess

```

**Comment by edublancas** [comment]
Unfortunately, yes. There's currently no way of changing the start method. But this looks like a simple change. We can add a new `start_method` argument to [Parallel](https://github.com/ploomber/ploomber/blob/6986b5f3f27b57ce9072e78a0472a89aa37206dc/src/ploomber/executors/parallel.py#L97)  and then configure the [ProcessPoolExecutor](https://github.com/ploomber/ploomber/blob/6986b5f3f27b57ce9072e78a0472a89aa37206dc/src/ploomber/executors/parallel.py#L198).

We'll add this to our backlog but if you wanna give it a try, that'd be great

**Comment by idomic** [comment]
@lambdaofgod feel free to try this functionality, we'll release it in the next cycle.
Keep providing valuable feedback!

**Comment by edublancas** [comment]
btw, to fix this once the new version is out:

```yaml
# pipeline.yaml

executor:
  dotted_path: ploomber.executors.Parallel
  processes: 2
  start_method: spawn
```
