### ISSUE TITLE
clarify in the docs that keys in the product field can be anything

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#888]
I got a user who asked me if their `pipeline.yaml` looked well and I noticed they had something like this:

```
tasks:
   # ... a bunch of tasks
   - source: fit.py
      product:
        nb: path/to/report.html
        data: path/to/data.csv
        data1: path/to/data.csv
        data2: path/to/data.csv
```

The user was confused and thought that the naming should be name, name1, name2. So we should add a little note in the basic concepts guide to explicitly say that keys can be anything

https://docs.ploomber.io/en/latest/get-started/basic-concepts.html

**Comment by edublancas** [comment]
sure!

**Comment by mhered** [comment]
Cool. Me pongo a ello.

**Comment by mhered** [comment]
Hi I reviewed the docs and I don't see immediately where to add the clarification in the basic concepts guide, I think perhaps it would make more sense to add it to the chapter that describes the syntax of `pipeline.yaml`, i.e. [here](https://docs.ploomber.io/en/latest/api/spec.html):
In the section on **tasks[*].product** it reads:
>...
> If the task generates multiple products, pass a dictionary:
 ```
tasks:
     - source: scripts/my_script.py
       product:
         nb: output/report.html
         data: output/data.csv
``` 
We could add something like: "Keys of the product dictionary can be chosen as desired so as to be descriptive of the outputs (e.g. `data`, `data_clean`, `model`, etc.)"

What do you think?

**Comment by mhered** [comment]
Ok I found this section of the basic guide:

> If the source script/notebook generates more than one output, create a dictionary under product:
```
tasks:
  - source: plot.py
    product:
      # if the script generates other products, use "nb" for the notebok
      nb: output/plots.ipynb
      # ...and any other keys for other files
      data: output/data.csv
```
Then we could also add here: "Keys of the product dictionary can be chosen as desired so as to be descriptive of the outputs (e.g. data, data_clean, model, etc.)"

If you agree I proceed to implement the two modifications (plus correcting some minor typos I have noticed)
