### ISSUE TITLE
Injecting parameters when the same notebook appears more than once

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#902]
To inject cells manually, users can run:

```
ploomber nb --inject
```

However, if the same source appears more than once. Ploomber will arbitrarily select one of the tasks and inject those parameters. Making it impossible to inject the parameters from other tasks that use the same template. Here's an example:

```yaml
tasks:
  - source: template.ipynb
     name: task-a
     product: report-a.ipynb
     params:
       some_param: a

  - source: template.ipynb
     name: task-b
     product: report-b.ipynb
     params:
       some_param: b
```

If we execute:

```
ploomber nb --inject
```

`template.ipynb` will have `some_param=b`, and there is no way to tell Ploomber to inject `some_param=a`.

We need the user to tell us which set of parameters they want to inject. I'm still unsure what's the simplest way (it has to be simple since this will be typed in the terminal). One approach I can think of is to add a new CLI argument (I'll call it `--priority` now for lack of a better name)

Example:

```
ploomber nb --inject --priority task-a
ploomber nb --inject --priority task-b
```

Since it might be that two or more notebooks are used as templates, `--priority` should be allowed to appear several times:

```
ploomber nb --inject --priority task-a --priority task-c
```

However, we'd need to validate that the values passed do not correspond to the same task. For example, this should throw an error:

```
ploomber nb --inject --priority task-a --priority task-b
```

(I'm not a fan of this approach so I'll keep thinking about what the best API is, suggestions welcome!)

Furthermore, we should throw a warning explaining to the user that since `template.ipynb` appears more than once, only one set of parameters will be visible. Something like:

> `template.ipynb` appears more than once in your pipeline, the parameters from `task-b` will be injected, to inject the parameters of another task, pass: `ploomber nb --inject --priority {task-name}`

**Comment by Wxl19980214** [comment]
@edublancas  Can you give me a user case on why a user would do something like this? 
```
tasks:
  - source: template.ipynb
     name: task-a
     product: report-a.ipynb
     params:
       some_param: a

  - source: template.ipynb
     name: task-b
     product: report-b.ipynb
     params:
       some_param: b
```

I mean no matter what we do, we can only have one param injected to our notebook because we only have one notebook? Eventually only one cell will be injected to our notebook, does give priority really matter? Why don't we just let user choose one to inject? For example, if we detected that there exist same template, we first output an error like this:
`Error, detected multiple injection to the same source notebook, use ploomber nb --inject --select {name} to specify which one to be injected`

and we implement the --select functionality to choose selected information to inject to the source notebook.

The mean thing is that I don't know why would user do this, and what should happen if user does this, for example, should multiple cells be injected? or should we make a copy of each different injections? I am a bit confused by this part.

**Comment by Wxl19980214** [comment]
@edublancas I think this is not achievable just by writing code in server side. We have to communicate between server and client and thus client must have some codes to receive the message we sent from server. I think we might need to implement a client side extension.

**Comment by edublancas** [comment]
> Can you give me a user case on why a user would do something like this?

Sure, this was a user request. If you're using the same notebook in multiple tasks, `--inject` will pick the first declared task and inject those parameters. However, you might want to inject other parameters if you're debugging the notebook (for example, if the notebook is failing only with certain set of parameters)

> I mean no matter what we do, we can only have one param injected to our notebook because we only have one notebook? 

Correct. There's only one notebook so we have to choose which set to inject.

> Eventually only one cell will be injected to our notebook,

Not really, when executing the pipeline, ploomber generates copies of the notebook. Following your example: report-a and report-b

> Why don't we just let user choose one to inject?

That's a fair point, the problem with `--select` is that this will only work when the user is manually injecting the cell. But the cell injection process also happens automatically when using the Jupyter plugin. In such case, they cannot do the `--select` thing.

> The main thing is that I don't know why would user do this, and what should happen if user does this, for example, should multiple cells be injected?

No, we should only choose a task and inject the parameters associated with it. Perhaps the confusion is coming from development vs execution. During execution, we generate multiple notebook copies, but this feature is exclusively for development purposes (hence, we only have a single copy).


I thought of a way of simplifying this:

We introduced [setup.cfg](https://docs.ploomber.io/en/latest/user-guide/jupyter.html#custom-jupyter-pipeline-loading) to manage some configuration and this fits well here. We can add a new parameter:

```
[ploomber]
entry-point = path/to/pipeline.yaml
inject-priority = *-suffix
```

It's important to allow wildcards here (the * character), since there might be pipelines that have more than one template:

```yaml
tasks:
  - source: one.ipynb
     name: one-a
     params:
       param: one-a

  - source: one.ipynb
     name: one-suffix
     params:
       param: one-suffix

  - source: another.ipynb
     name: another-a
     params:
       param: another-a

  - source: another.ipynb
     name: another-suffix
     params:
       param: another-suffix

```

With this config, opening another.ipynb will inject `one-suffix` to `open.ipynb` and `another-suffix` to `another.ipynb`.
