### ISSUE TITLE
`ploomber nb --format py` breaks the pipeline

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#908]
The current implementation for re-formatting does a search and replace. The problem is that this will change the product as well. Example

```yaml
tasks:
  - source: something.ipynb
     product: something.ipynb
```

becomes:

```yaml
tasks:
  - source: something.py
     product: something.py
```

after running `ploomber nb --format py`. the problem is that a `.py` is not recognized as a valid product.

perhaps the search and replace should look for `source: something.ipynb`
