### ISSUE TITLE
scaffold on .html source tried to create the module

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#929]
When running scaffold on this pipeline.yaml:

```
tasks:
  - source: sample.html
    product: output/nb.ipynb
    name: sample
```

We get a `sample.py` file with this content:

```
def html(product):
    """Add description here
    """
    # extract_upstream=True in your pipeline.yaml file, if this task has
    # dependencies, add an "upstream" parameter to the function
    # and declare them here (e.g. upstream['some_task'])
    pass
```

scaffold thinks it's a dotted module instead of disqualifying this as a source. We have a similar issue for the task build - #646 .
