### ISSUE TITLE
feature idea: notebook inplace execution

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#941]
Currently, we have a separation between the source and product notebook. But some users might prefer to keep everything in a single place. Furthermore, this also simplifies the explanation of how ploomber works for newcomers. We could allow something like this:

```
tasks:
  - source: first.ipynb
     product:
       data: raw.csv

  - source: clean.ipynb
     product:
       data: clean.csv
```

Since the `product.nb` does not exist, this implies that we should execute the notebooks inline and the output cells stored there.
