### ISSUE TITLE
Proposal - Support for SQL on Flat Files (CSV and Parquet)

### ISSUE THREAD

**Issue by kvnkho** [ploomber/ploomber#944]
Hi friends!

Kevin from the [Fugue Project](https://github.com/fugue-project/fugue/) here. 

Ploomber has a nice abstraction for [SQL tasks inside pipelines](https://docs.ploomber.io/en/latest/get-started/sql-pipeline.html). Users can use either the `SQLAlchemyClient` or the `DBAPIClient` to connect to databases and run their queries. I think we can use a similar semantic for running SQL queries on top of flat files (csv, parquet) using [FugueSQL](https://fugue-tutorials.readthedocs.io/tutorials/fugue_sql/index.html). We can make a general base class though that the `FugueClient` could inherit.

FugueSQL is an abstraction layer that lets users use SQL queries on top of Pandas, Spark, and Dask DataFrames. We also support [DuckDB](https://duckdb.org/) as a backend. Using FugueSQL, users would be able to perform SQL queries as SQL Tasks after the Python Tasks in a Ploomber pipeline.

Below is a quick example on what FugueSQL looks like. It is ANSI SQL compatible for the most part except that there are added keywords to make it capable of being an end to end interface. Note that `ALTER COLUMNS` below is needed because Pandas reads everything as a string.

```python
import pandas as pd 

df = pd.DataFrame({"a": [1,2,3], "b": [1,2,3]})
df.to_csv("test.csv", index=False)

from fugue_sql import fsql
query = """
df = LOAD "/Users/kevinkho/Work/ploomber/demo/products/test.csv" (header=true)
df2 = ALTER COLUMNS a:int, b:int FROM df

SELECT * FROM df2
 WHERE a > 2

SAVE OVERWRITE "/Users/kevinkho/Work/ploomber/demo/products/test2.csv" (header=true)
"""
fsql(query).run()
```

In order to run this on Dask, you could do:
```
fsql(query).run("dask")
```
and it would use Dask DataFrames to perform the operations instead. Similarly, you could use `"spark"` as the engine.

If there was a `FugueClient`, a pipeline could look like this:
```yaml
tasks:

  - source: test.py
    product: 
      nb: products/test.ipynb
      data: products/test.csv

  - source: example.sql
    client: clients.FugueClient
    product: [/Users/kevinkho/Work/ploomber/demo/products/test2_sql.csv, table]
```

I have tested this naive `FugueClient` prototype and it actually works already with some caveats (to be explained later).
```python
from ploomber.clients.client import Client
class FugueClient(Client):

    def __init__(self, engine=None, engine_kwargs=None):
        super().__init__()
        self.engine = engine
        self.engine_kwargs = engine_kwargs or dict()

    def execute(self, code):
        from fugue_sql import fsql 
        fsql(code).run(self.engine)
```
I just modified the SQL query a bit to chain with `upstream` and `product`:
```sql
df = LOAD "{{upstream['test']['data']}}" (header=true)
df2 = ALTER COLUMNS a:int, b:int FROM df

SELECT * FROM df2
 WHERE a > 2

SAVE OVERWRITE "{{product}}" (header=true)
```

**And it all works already!**

If you are interested, there are just some points of refinement.
1. The above runs with an error saying that no `table` or `view` is created. The default `SQLRelation` assumes one of these. I think we could just make another `products.FileRelation` or something like that to use in conjunction with with model.
2. It seems the assumption of the SQL design is one output table at the moment. It makes sense for traditional SQL but we can actually have multiple `SAVE` commands in one query. This can remove redundant calculation of intermediate steps for two output tables.

Let me know your thoughts!

**Comment by edublancas** [comment]
Hi, this is great - let's do this!

> The above runs with an error saying that no table or view is created. The default SQLRelation assumes one of these. I think we could just make another products.FileRelation or something like that to use in conjunction with with model.

Yes, the [SQLScript](https://github.com/ploomber/ploomber/blob/2fe474987ae6fca088e02399dbff99672a17fc95/src/ploomber/tasks/sql.py#L17) task validates that the table is created, the validation is performed by the [source object](https://github.com/ploomber/ploomber/blob/2fe474987ae6fca088e02399dbff99672a17fc95/src/ploomber/tasks/sql.py#L141). We can create a new SQL task whose output is a file. Not sure what's the best name here. Maybe `SQLScriptFile` (?) - that can generate a [File](https://github.com/ploomber/ploomber/blob/2fe474987ae6fca088e02399dbff99672a17fc95/src/ploomber/products/file.py#L20) as a product. The existing implementation of [SQLDump](https://github.com/ploomber/ploomber/blob/2fe474987ae6fca088e02399dbff99672a17fc95/src/ploomber/tasks/sql.py#L145) can be used as inspiration since that one takes a SQL script and dumps the results to a local file.

> It seems the assumption of the SQL design is one output table at the moment. It makes sense for traditional SQL but we can actually have multiple SAVE commands in one query. This can remove redundant calculation of intermediate steps for two output tables.

We can support multiple output files as well. See example below

## interface

a `pipeline.yaml` would look like this

```yaml
tasks:
  - source: script.sql
     product: some-file.parquet
     task_class: SQLScriptFile
     client: clients.fugue_sql
```

if generating more than one file:

```yaml
tasks:
  - source: script.sql
     product:
       some-file: some-file.parquet
       another-file: another-file.parquet
     task_class: SQLScriptFile
     client: clients.fugue_sql
```

once this is working, we can modify the [class](https://github.com/ploomber/ploomber/blob/master/src/ploomber/spec/dagspec.py) that parses the pipeline.yaml so it automatically sets the `task_class` if it has a SQL file in the source and a flat file in the product.
