### ISSUE TITLE
confusing `grid` behavior due to recent change

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#952]
In [0.19.8](https://github.com/ploomber/ploomber/blob/master/CHANGELOG.md#0198-2022-07-16) we introduced support for dotted paths in `grid`, this implies that values that point to functions/classes are not interpreted as literals, but imported, called and the returned value is used.

Example:

```yaml
tasks:
  - source: source.ipynb
    product: out.ipynb
    grid:
      key: functions.generate_numbers
      another: [1, 2, 3]
```

In this case, if there is a `functions.py` with the function `generate_numbers`, ploomber will call it and assign the returned value to `key`. However, there might be cases where the user wants to pass the dotted path as-is, currently the solution is to pass the string as a list with one element but this will be confusing to users. I'm unsure what's the best solution. Perhaps adding a note at the end of the error saying: "if you meant to pass the string literally, pass it as [string]"
